### PR TITLE
bradl3yC - update build

### PR DESCRIPTION
**Pull request by bradl3yC**
Needed to run yarn build before merging

### CODE REVIEW

**Comment by kevinmirc** [comment]
@bradl3yC vets-API tests are failing because this new property is required. Is there a vets-api PR open for this change?

@bkjohnson It looks like your vets-api PR (https://github.com/department-of-veterans-affairs/vets-api/pull/4185) is also failing from the same issue.

```js
// spec/request/swagger_spec.rb
{
  "errors": [
    {
      "title": "Validation error",
      "detail": "The property '#/application/veteran' did not contain a required property of 'ethnicity' in schema 00161862-3cee-5a10-89fb-4815fc7cd22d",
      "code": "109",
      "status": "422"
    }
  ]
}
```

**Comment by bradl3yC** [comment]
@kevinmirc yeah that frontend work was done by our team for another team - They did not ask us to do any BE work.  I will have to mention it to them.

**Comment by jholton** [comment]
Do you have a link to a related GH issue for more context?

**Comment by kevinmirc** [comment]
Here's the fix: https://github.com/department-of-veterans-affairs/vets-api/pull/4187

**Comment by kevinmirc** [comment]
This change has been reversed in 5.0.1 https://github.com/department-of-veterans-affairs/vets-json-schema/commit/0a1dbc9ba6cf0177a60ca216f74b3eaed6241271

**Pull request merged**
