### PR TITLE
IRIS Ask a Question form schema update

### PR DESCRIPTION
**Pull request by shefalinayak**
# New schema

department-of-veterans-affairs/orchid#88

## Pull Requests to update the schema in related repositories

department-of-veterans-affairs/vets-website#0000
department-of-veterans-affairs/vets-api#0000

### CODE REVIEW

**Review by rianfowler — APPROVED** [review]

**Comment by kevinmirc** [comment]
@shefalinayak, @anitadewitt-va [vets-api](https://github.com/department-of-veterans-affairs/vets-api) has a fixture for this schema that uses the removed enum **Policy Questions**. This is making the test suite fail. Do you have a vets-api PR to resolve this?

Fixture: `spec/fixtures/ask/minimal.json`
Failing Spec: `spec/controllers/v0/ask/asks_controller_spec.rb:24`

**Comment by kevinmirc** [comment]
@shefalinayak, @anitadewitt-va I have a vets-api PR with a fix, but I need your approval since I don't have any context to these features and changes: https://github.com/department-of-veterans-affairs/vets-api/pull/4951

**Comment by shefalinayak** [comment]
@kevinmirc Thanks for catching that and making the PR. We hadn't made a vets-api PR for this yet, sorry that it was blocking your own changes!

**Comment by kevinmirc** [comment]
No problem, @shefalinayak! Thanks for the quick response and review.

**Pull request merged**
