### PR TITLE
Preneed consistency updates ceh

### PR DESCRIPTION
**Pull request by cehsu**
Fixes full name overwrite bug from https://github.com/department-of-veterans-affairs/vets-json-schema/pull/164.

### CODE REVIEW

**Comment by jbalboni** [comment]
@cehsu Can you update the version in package.json?

**Comment by cehsu** [comment]
Thanks Jeff, updated.

**Comment by jbalboni** [comment]
@cehsu There's a typo in it :-)

**Comment by cehsu** [comment]
Thanks again @jbalboni, fixed.

**Pull request merged**
