### PR TITLE
Add graduation expected date

### PR DESCRIPTION
**Pull request by annekainicUSDS**
Added a graduation expected date. Not sure if I updated the package version correctly, so let me know :)

### CODE REVIEW

**Comment by lihanli** [comment]
highSchoolOrGedCompletionDate is supposed to be the graduation expected date, the name is unclear because the field name is copied from the 1990

**Comment by markolson** [comment]
Using `highSchoolOrGedCompletionDate ` would fill in this date in the "Applicant's date of disposition: " field of the spool file. Did we want different language around that, @annekainicUSDS?

**Comment by annekainicUSDS** [comment]
Ah okay, I was thinking it was only used for a past graduation date. But you're right I could use it for a future date too. Just need to change the front-end validations based on the situation. So a schema change might not be needed then?

**Comment by markolson** [comment]
I think that's right, just sent it over as the `highSchoolOrGedCompletionDate` and we're good!

**Comment by annekainicUSDS** [comment]
Perfect! Will close this PR then.

**Pull request closed without merging**
