### PR TITLE
Add tera questions to 1010EZR schema

### PR DESCRIPTION
**Pull request by lihanli**
# New schema
Add tera questions to 1010EZR schema

https://github.com/department-of-veterans-affairs/va.gov-team/issues/77574

## Pull Requests to update the schema in related repositories
_After you've merged your changes to vets-json-schema you'll need to make PR's to vets-website and vets-api. Please link them here._

- https://github.com/department-of-veterans-affairs/vets-api/pull/
- https://github.com/department-of-veterans-affairs/vets-website/pull/

### CODE REVIEW

**Review by JoshingYou1 — APPROVED** [review]
LGTM! Great work Lihan!

**Comment by ryan-mcneil** [comment]
@lihanli Can you please check out the gemfile conflict and we'll get this moving. Thanks!

**Comment by lihanli** [comment]
@ryan-mcneil ok i fixed it, thanks

**Review by ryan-mcneil — APPROVED** [review]
👍

**Pull request merged**
