### PR TITLE
Update 10-10CG to allow only one caregiver: Primary or SecondaryOne

### PR DESCRIPTION
**Pull request by kevinmirc**
Fixes: https://github.com/department-of-veterans-affairs/va.gov-team/issues/15266
Related to: https://github.com/department-of-veterans-affairs/va.gov-team/issues/12961

**Description**
Update the 10-10CG schema to allow applications without a PrimaryCaregiver. If no PrimaryCaregiver provided a SecondaryCaregiverOne is required.

Create a functional version of `SchemaTestHelper` that provides more context on failed expectations.

**Summary**
- [x] Add conditional validation on Primary Caregiver's and Secondary Caregiver's presence.
- [x] Add specs to test data for:
  - [x] Vet and PC only
  - [x] Vet and SC1 only
  - [x] Vet and SC1 and SC2
  - [x] Vet and PC and SC1
  - [x] Vet and PC and SC1 and SC2
- [x] Add a functional version of SchemaTestHelper
- [x] Refactor 10-10CG specs to be more explicit by using SchemaTestHelper

## Pull Requests to update the schema in related repositories
Website [Front-end changes not required]
- [x] Tests pass

API https://github.com/department-of-veterans-affairs/vets-api/pull/5264
- [x] Tests pass

### CODE REVIEW

**Review by LinnJS — APPROVED** [review]
I ran Unit Test, E2E test, and manually tested locally. All instances passed once I pulled the latest of the betamocks repo.

**Review by kfrz — APPROVED** [review]
Looks good.

**Review by Clark-W-Griswold — APPROVED** [review]
👍

**Comment by kevinmirc** [comment]
Fixes: https://github.com/department-of-veterans-affairs/va.gov-team/issues/7429

**Pull request merged**
