### PR TITLE
Add new dependent options

### PR DESCRIPTION
**Pull request by rlbaker**
* Adds Father, Mother, Spouse and Other as relationship options in `common/constants.js`
* Rebuilt JSON schemas
* Bumps version to 3.4.0

### CODE REVIEW

**Comment by rlbaker** [comment]
@jbalboni Do you think I should be renaming the field names to match the fact that it is no longer a "Child" relationship?

**Comment by jbalboni** [comment]
@rlbaker I'm a little hesitant, since it makes this change more complicated. To change the field name we have to:

1. Update the schema to include both field names
2. Update the backend to use dependentRelationship by default, but fall back to childRelationship
3. Update the front end form config to use the new name and write a migration for saved data
4. Update the schema to remove the old name
5. Update the backend to remove the old name

We probably should change it, though, it'll be less confusing later. Unless @lihanli has a strong opinion either way.

**Comment by lihanli** [comment]
i think we should change it, should be low priority though

**Comment by jbalboni** [comment]
Alright, we can make separate tech debt item for that and change it later.

**Comment by jbalboni** [comment]
Debt issue: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/4924

**Pull request merged**
