### PR TITLE
Move checks from CircleCI to GHA

### PR DESCRIPTION
**Pull request by timwright12**
The vets-json-schema repo CI was never moved over to GHA from CircleCI. There was a security issue found related to CircleCI, and it's best that we move ALL repos over to the GHA CI based on the documented findings. According to the product doc, be-tools has ownership of the vets-json-schema repo

Additionally, we've seen issues lately where the CircleCI runs are "stuck" and cannot be re-triggered without platform intervention due to GH teams based permission errors.

https://github.com/department-of-veterans-affairs/va.gov-team/issues/32509

### CODE REVIEW

**Comment by jmbosse19** [comment]
Successful run [here](https://github.com/department-of-veterans-affairs/vets-json-schema/actions/runs/1440919994) of GHA. This work was done by Tim Wright but just confirming that what he did satisfies the requirement for moving from Circleci for this repo per [this ticket](https://app.zenhub.com/workspaces/vsp---backend-tools-6019ab9387ae890011e05e73/issues/department-of-veterans-affairs/va.gov-team/32509).

**Comment by jmbosse19** [comment]
Only question I have is if this should be on PR or just any push?

**Comment by timwright12** [comment]
@jmbosse19 it would run on push so we can recheck the build on each change

**Comment by rileyanderson** [comment]
> Only question I have is if this should be on PR or just any push?

I think we should run it on `push`

**Comment by jmbosse19** [comment]
> @jmbosse19 it would run on push so we can recheck the build on each change

thanks. It was on PR, so I changed it to push.

**Review by rileyanderson — APPROVED** [review]
LGTM. After this is merged we will need to remove `Required` from CircleCI check and add it to this GHA check. I don't have the permissions to do this so we will need to find out who can

**Comment by jmbosse19** [comment]
> LGTM. We will need to remove `Required` from CircleCI check and add it to this GHA check. I don't have the permissions to do this so we will need to find out who can

I'm asking Fleet about that, I'll make sure that's done.

**Pull request merged**
